name: provider_screen
description: Boost productivity and enhance code readability with a simplified screen creation package based on Flutter's Provider state management.
version: 1.0.2
homepage: https://github.com/Xim-ya/provider_screen

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter


